---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/users/{user_id}/posts/{post_id}/comments":
    get:
      summary: Retrieves comments for a post
      tags:
      - Comments
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      - name: post_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: comments found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        body:
                          type: string
                      required:
                      - id
                      - body
    post:
      summary: Creates a new comment
      tags:
      - Comments
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      - name: post_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '201':
          description: comment created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
              required:
              - body
  "/api/v1/users/{user_id}/posts":
    parameters:
    - name: user_id
      in: path
      required: true
      schema:
        type: string
    get:
      summary: Retrieves all posts for a user
      tags:
      - Posts
      responses:
        '200':
          description: Posts found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        title:
                          type: string
                        author_id:
                          type: integer
                        text:
                          type: string
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
